# Generated by Django 5.0.2 on 2024-03-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sesion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuCatEstado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strNombreEstado', models.CharField(max_length=20)),
                ('strDescripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UsuCatEstado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuCatTipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strTipoUsuario', models.CharField(max_length=50)),
                ('strDescripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UsuCatTipoUsuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strNombre', models.CharField(max_length=20)),
                ('strPassword', models.CharField(max_length=20)),
                ('idUsuCatEstado', models.IntegerField()),
                ('idUsuCatTipoUsuario', models.IntegerField()),
            ],
            options={
                'db_table': 'UsuUsuario',
                'managed': False,
            },
        ),
    ]
