# Generated by Django 5.0.2 on 2024-03-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProCatCategoria',
            fields=[
                ('idCat', models.AutoField(primary_key=True, serialize=False)),
                ('strNombreCategoria', models.CharField(max_length=100)),
                ('strDescripcionCategoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'procatcategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProCatSubCategoria',
            fields=[
                ('idSubCat', models.AutoField(primary_key=True, serialize=False)),
                ('strNombreSubCategoria', models.CharField(max_length=100)),
                ('strDescripcionSubCategoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'procatsubcategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idPro', models.AutoField(primary_key=True, serialize=False)),
                ('StrNombrePro', models.CharField(max_length=100)),
                ('StrDescriptcion', models.CharField(max_length=255)),
                ('decMaximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('decMinimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curPrecio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('blodImage', models.BinaryField(null=True)),
                ('strUrlImage', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'proproducto',
                'managed': False,
            },
        ),
    ]
