# Generated by Django 5.0.2 on 2024-03-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0003_procatcategoria_procatsubcategoria_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
    ]
