# Generated by Django 5.0.2 on 2024-03-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0004_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
