# Generated by Django 5.0.2 on 2024-03-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0005_alter_producto_options'),
    ]

    operations = [
    ]
