# Generated by Django 5.0.3 on 2024-04-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0006_auto_20240317_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenVenta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False)),
                ('strFolio', models.CharField(max_length=30, null=True)),
                ('dtFecha', models.DateField(null=True)),
            ],
            options={
                'db_table': 'venventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenVentaCategoria',
            fields=[
                ('idVenCat', models.AutoField(primary_key=True, serialize=False)),
                ('strNombreVentaCategoria', models.CharField(max_length=20)),
                ('srtDescripcionVentaCategoria', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'venventacategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenVentaProducto',
            fields=[
                ('idVenPro', models.AutoField(primary_key=True, serialize=False)),
                ('idVenVenta', models.IntegerField()),
                ('idProProducto', models.IntegerField()),
                ('decCantidad', models.DecimalField(decimal_places=0, max_digits=10)),
                ('curTotal', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'venventaproducto',
                'managed': False,
            },
        ),
    ]
